### PR TITLE
LRDOCS-8846 Upload Backup UI

### PR DESCRIPTION
**Pull request by Alec-Shay**
See: https://issues.liferay.com/browse/LRDOCS-8846
EDIT: also covers: https://issues.liferay.com/browse/LRDOCS-8802

This adds documentation for the new method of uploading backups through a UI. This will eventually need to be updated to indicate `.gz` archives instead of `.tgz`, but it looks like for the initial release it will still be `.tgz` archives supported for upload.

One thing I was a bit unsure of is if this feature's release means we should remove the section for the APIs, since it seems there is a UI method available for both download and upload now (since we are generally avoiding documenting the APIs where they are not needed). I kept it in place since they were already documented previously, and since I guess it might still be preferable for someone, but I could remove this if need be. Since both methods are represented in this article, I also extracted the information on compressing the DB and DL into a separate section toward the end of the article.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Update: support for `.gz` uploads and downloads will be available with the release after all, so I added more changes for that here.

Also, since it's very related (and I threw in the slight command rewrite it also asks for), this PR can also cover [LRDOCS-8802](https://issues.liferay.com/browse/LRDOCS-8802).

**Review by zenorocha — APPROVED** [review]

**Comment by Alec-Shay** [comment]
@jrhoun Cloud team review's completed, when you get a chance to look at this.

Also, for future reference, this is documentation for the feature in a soon-to-come release currently slated for **Thursday, Feb. 11** (so we'll want to wait to push this to prod 'til then).

**Comment by jrhoun** [comment]
Merged. Thanks.

**Pull request closed without merging**
