### PR TITLE
LRDOCS-8526 Questions App Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8526

@mtokudome

- initial files and file structure
- initial images and md file
- fixed numbered lists
- removed defintion bullets
- LRDOCS-8526 Reorganized files.
- LRDOCS-8526 Add Questions to RST
- LRDOCS-8526 Wordsmithing.

### CODE REVIEW

**Comment by jrhoun** [comment]
@mtokudome - was it intentional to not include some of the configuration related information from the draft in this pull? (Referring to https://github.com/LuismiBarcos/questions-docs/blob/master/README.md#configuration)

**Comment by mtokudome** [comment]
> @mtokudome - was it intentional to not include some of the configuration related information from the draft in this pull? (Referring to https://github.com/LuismiBarcos/questions-docs/blob/master/README.md#configuration)

Good question, I think I wasn't quite sure the scope of this article. Do you want me to add that section? @jrhoun

**Comment by jrhoun** [comment]
Hey @mtokudome - let's create a ticket (LRDOCS) that covers the missing information -- that way we don't forget about it. That will also let me continue with reviewing this pull and pushing it forward. I'll leave it up to you how we should cover the configuration related information -- either in the same article, or in a new one like "Configuring the Questions Application".

For context: what led me to review the original draft was a question that came up in my mind about how someone would implement this application for themselves to create a question/answer forum. Specifically: "How would someone moderate questions / responses?" That opened up a line of thinking about -- how banning users is handled, how are email notifications (if there are any) handled? (in that case, I presume that it would be similar to how we handle message boards).

**Comment by mtokudome** [comment]
Sounds good. Created a ticker for future article: https://issues.liferay.com/browse/LRDOCS-8650

**Comment by jrhoun** [comment]
Merged. Thanks. See my changes: f8f57fd88f6d133d06f516820af23084f81d84fe

**Pull request closed without merging**
