### PR TITLE
LRDOCS-9188 Docment Fragment Propagation

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-9188

@jorge-campo

- LRDOCS-9188 First draft.
- LRDOCS-9188 Update placeholder .rst file
- LRDOCS-9188 minor updates to clarify Propagation options
- LRDOCS-9188 include SME review comments.
- LRDOCS-9188 Wordsmithing.

### CODE REVIEW

**Comment by jrhoun** [comment]
_Hm_. So as I was reviewing this I noticed that we _seem_ to have this content documented here: https://github.com/liferay/liferay-learn/blob/master/docs/dxp/latest/en/site-building/displaying-content/using-fragments/propagating-page-fragment-changes.md

Therefore, this _seems_ duplicative to me, which is a frustrating possibility. If it is, I would assume that we might want to consider merging the content into one article. @jorge-campo what do you think?

**Comment by jorge-campo** [comment]
Thanks for bringing this @jrhoun! That's... surprising. This was a request from the PM, and neither he nor I could find that content in Liferay Learn. Of course, I will check the existing doc and combine the information with my doc. I will send a new PR to you. Feel free to cancel this PR.

**Comment by jrhoun** [comment]
Thanks @jorge-campo. I had a feeling as I was reviewing it that I had seen something about it before, so I did a local file search for 'propagation' and found it. Look forward to the next one. :)

**Comment by jorge-campo** [comment]
Superseded by https://github.com/sez11a/liferay-learn/pull/461 (cc @jrhoun).

**Pull request closed without merging**
