### PR TITLE
Configuring portlets, themes, and layout templates

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@jhinkey Hmmmm... I have one real concern with this, and it's one I'm not entirely sure how to address yet.

Namely, it's that our own terminology that we are trying to reinforce in our documentation is at odds with DXP's UI; it's calling "portlets" what we specifically want to refer to as "widgets." On its very face that's confusing. I was originally just going to suggest you replace all instances of "portlet" in this article with "widget," but now that would create a disconnect. Since we don't really refer to them as portlets in general this is already going to be disorienting for the reader because we otherwise don't really need to use the word "portlet" unless we're talking about portlet specifications or code. I almost even feel the urge to bonk someone on the head to change the word in the product.

Feel free to share thoughts if you have any. Maybe one idea could be to change "Portlets" to "Widgets" in the title, but then in the body of the article, just touch on that quickly (i.e., "configure widgets (shown as 'Portlets' in the UI), themes, ...").

**Comment by jhinkey** [comment]
@Alec-Shay I can understand the frustration. I agree that the UI should use the term _Widgets_ instead of _Portlets_ and that of course, the docs should do the same. But for now, I think they need to stay consistent. I'll bring it up with the Core Infra team.

I know underneath every Widget there's actually a Portlet, but I think that the UI is for our admin users--and they don't know or care about portlets. They know widgets.

**Comment by Alec-Shay** [comment]
@jhinkey Exactly. Thanks for bringing it up with the team, hopefully something comes of it (I'm not sure what the implications would be if they do decide to change and then backport it, and then we have different words in different releases of the product -- but in any case, correct in some version is better than wrong in every version).

**Comment by jhinkey** [comment]
superseded by https://github.com/jhinkey/liferay-learn/pull/4

**Pull request closed without merging**
