### PR TITLE
LRDOCS-8726 Sites Dashboard Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8726

@mtokudome

- initial md file and directory structure
- initial sites-dashboard.md draft and section removed from touchpoints.md
- updated touchpoints.md article
- wordsmithing
- fixed link
- LRDOCS-8726 Wordsmithing.
- LRDOCS-8726 Wordsmithing.

### CODE REVIEW

**Comment by jrhoun** [comment]
Hi @mtokudome -- how does the material covered in "Sites Dashboard" relate to this article: ["Viewing the Analytics Dashboard"](https://learn.liferay.com/analytics-cloud/latest/en/getting-started/quick-tour/viewing-the-analytics-dashboard.html)? It seems...at least partially duplicative - but that's just my own initial impression.

**Comment by mtokudome** [comment]
> Hi @mtokudome -- how does the material covered in "Sites Dashboard" relate to this article: ["Viewing the Analytics Dashboard"](https://learn.liferay.com/analytics-cloud/latest/en/getting-started/quick-tour/viewing-the-analytics-dashboard.html)? It seems...at least partially duplicative - but that's just my own initial impression.

There might be a little overlap but my Sites Dashboard article explains each panel in detail.

**Comment by mtokudome** [comment]
Superseded by [jrhoun#873](https://github.com/jrhoun/liferay-learn/pull/873)

**Comment by jrhoun** [comment]
Closing as this was merged here: https://github.com/jrhoun/liferay-learn/pull/873

**Pull request closed without merging**
