### PR TITLE
Upgrade section more edits

### PR DESCRIPTION
**Pull request by Alec-Shay**
Here's a bunch more edits including those addressing various points of feedback:

This includes:

- Going through and addressing the various comments left in the upgrade docs
- Adding a bit more information on `blade upgradeProps`: 
df27aea  (@achaparro -- Is this more along the lines of what you were hoping for? Or would you like to see still more?)
- Correcting information in the deprecated apps article: 
bc23b0e  (@nicolelau -- FYI)
- Fixing links (and some typos) in the Planner steps (in the reference section outside the actual upgrade section): 
7ad3355  (@jhinkey -- I also noticed as we make more changes, we diverge further from the flow in the Planner steps. I'm not sure if this is a problem or not, but do you know who we might reach out to to check?)

### CODE REVIEW

**Comment by jrhoun** [comment]
Merged. Thank you!

**Comment by achaparro** [comment]
Hey @Alec-Shay,

```
Adding a bit more information on blade upgradeProps:
df27aea (@achaparro -- Is this more along the lines of what you were hoping for? Or would you like to see still more?)
```
I think that's enough, thanks!

**Comment by jhinkey** [comment]
@Alec-Shay I checked the Upgrade Planner Steps again. The steps and the order their in is still appropriate. The steps haven't changed and they're the same ones Alberto reviewed last year. 

The upgrade articles are organized in a manner that flows well for reading and understanding the concepts. The steps provide a comprehensive way of iterating over the topics (albeit in varying order) to test upgrading and upgrade the production installation. It's good. Thanks.

**Comment by Alec-Shay** [comment]
@jhinkey Alright. I just wanted to be sure, since it seemed like some of the steps were following the order of certain articles, and I wasn't sure if that might be important to us. Thanks for checking again and confirming.

**Pull request closed without merging**
