### PR TITLE
LRDOCS-9583 Code snippet Copy button is misaligned

### PR DESCRIPTION
**Pull request by rdai10**
https://issues.liferay.com/browse/LRDOCS-9583

### CODE REVIEW

**Comment by jrhoun** [comment]
Hi @rdai10 the alignment looks solved! The coloration though does still look a little odd -- do you think that it looks right? 
image

**Comment by rdai10** [comment]
@jrhoun what did the colors look like originally? If you can provide me with a frame of reference, I can make a follow up change.

**Comment by jrhoun** [comment]
Found the OG pull here: https://github.com/jrhoun/liferay-learn/pull/377 . References https://github.com/executablebooks/sphinx-copybutton

image

**Comment by jrhoun** [comment]
image

**Comment by rdai10** [comment]
Looks like the pr from https://github.com/jrhoun/liferay-learn/pull/377 replaced the default copy button with a white icon to match the `code` style and left the hover background color to the default gray, which is what you see now.

Do you want to change the background color of the copy button on hover so there is more contrast? A few options:
option 1:
image
option 2: 
image

**Comment by jrhoun** [comment]
Sorry for the delay @rdai10 . I think the first option is preferable to me.

**Comment by rdai10** [comment]
Updated!
image

**Comment by jrhoun** [comment]
Merged. Thank you!

**Pull request merged**
