### PR TITLE
Ported Security Docs

### PR DESCRIPTION
**Pull request by sez11a**
These docs currently go in Installation and Upgrades. I attempted to make these click-merge friendly, but please review and let me know what needs to be changed to conform them to our evangelistic message. :-)

### CODE REVIEW

**Comment by jrhoun** [comment]
One question that I've been struggling with, for this overview article is the h2 headers - they seem to currently represent different types of information, and as a reader, it's confusing to go between them.

**Authentication** and **Authorization**

Seem like peas on a pod. But seems dissonant with **Permissions Checking** which seems dissonant with **Web Services**. Permissions checking seems like a _type_ or Authorization to me? **Authorization** and **Authentication** both seem to have application to **Web Services**. This question though is based on the following knowledge assumptions I have:

If Authentication = Who are you and how do I determine who you are
and if
Authorization = Now that I know who you are, what can you and can't you do

Does that make sense? I think those are the big questions that affect how cohesively the overview comes together in my mind - is tripping over how the major sections of the article are organized and presented. Let me know what you think!

**Comment by jrhoun** [comment]
There are a few more medium / smaller things that I would change, but the most substantive and consequential area is how the "Securing Liferay" overview structures the concepts and tees up the other articles that are included in the pull. I'm going to hold off further review until we can maybe sync about my prior comment. Thanks @sez11a .

**Comment by sez11a** [comment]
Hey @jrhoun , 

The first article is an introduction to Liferay security as a topic. The components of Liferay security are authentication, authorization (two different topics in the security world), permission checking, web services (as in, how do we lock down web services so a Liferay installation isn't "leaking" data), and portal properties that configure how your Liferay installation behaves. 

Authentication defines **who** the user is; authorization defines **what** a user has access to. These headings will be instantly recognizable (and even expected) by security professionals reviewing our documentation, because they're used to [seeing it](https://www.okta.com/identity-101/authentication-vs-authorization/) [all over](https://medium.com/datadriveninvestor/authentication-vs-authorization-716fea914d55) [the place](https://auth0.com/docs/authorization/concepts/authz-and-authn). 

Liferay's permissions system is a component of our security system, and is documented in this section (though not in the files in this PR). It's how you define in the code who is authorized to do what (i.e., *permissions*). 

Another thing security professionals want to know up front is how can you lock down the system? So we show the security layers for web services (notorious for leaking data when not properly configured) at a high level up front, inviting them to read the details in the articles that follow. 

It all comes out of knowing who your audience is and what they want to know. Then you summarize it so they can get an idea of the content quickly.

**Comment by jrhoun** [comment]
Looks like this was closed on accident because a commit fixing github issue #10 was closed. Reopening.

**Comment by jrhoun** [comment]
Merged with changes. See https://github.com/jrhoun/liferay-learn/commit/42ee1a09793879665a58dd0ecb2b5b0e670cc31e

**Pull request closed without merging**
