### PR TITLE
liferay-learn site | update tokens | LRDOCS-0000

### PR DESCRIPTION
**Pull request by rbohl**
I do not know what to do with the reference doc zip token, or the commerce tokens (commerce is now bundled).
cc @sez11a

### CODE REVIEW

**Comment by rbohl** [comment]
This CI error looks related to the refdocs, btw (not sure if I caused it or if it's the same one we've been experiencing):
```
ERROR: liferay-ce-portal-doc.zip

liferay-ce-portal-doc.zip
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
Open ERROR: Can not open the file as [zip] archive
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (50654),ASM,AES-NI)



Scanning the drive for archives:
ERRORS:
1 file, 9 bytes (1 KiB)
Is not archive

Extracting archive: liferay-ce-portal-doc.zip

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
Error: Process completed with exit code 2.
```

**Comment by rbohl** [comment]
@jrhoun I just pushed up a test commit--I want to see what CI does with it. Stand by.

**Comment by rbohl** [comment]
Interesting:
```
ERROR: liferay-ce-portal-doc.zip

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (50654),ASM,AES-NI)
liferay-ce-portal-doc.zip

Open ERROR: Can not open the file as [zip] archive
Scanning the drive for archives:

1 file, 9 bytes (1 KiB)


Extracting archive: liferay-ce-portal-doc.zip

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERRORS:
Is not archive
Error: Process completed with exit code 2.
```

**Comment by rbohl** [comment]
I don't know about this refdoc process. If you know what's up feel free to suggest something, otherwise maybe we wait for Rich to return? I don't think I can look into it today.

**Comment by sez11a** [comment]
@rbohl This means it did not successfully download the reference doc .zip file, which probably means the token is wrong. Compare the file name it's trying to download with the one that's out on GitHub.

**Comment by rbohl** [comment]
Thanks to @sez11a pointing me in the right direction, the last commit passed CI--it's all yours, JR. Just remember I didn't touch the commerce tokens.

**Comment by jrhoun** [comment]
Merged. Thanks.

**Comment by jrhoun** [comment]
@rbohl no need to worry about the commerce tokens b/c they are only used by a 'legacy' part of the commerce docs. The up to date commerce install docs reference the liferay portal/dxp install docs.

**Pull request closed without merging**
