### PR TITLE
72 Site Building User Guide Echo docs port

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jrhoun Here is my first pass at the Site Building section. Along with the relative images folder for the Site Building section, I've also added an images folder in the 7.2.x folder to hold shared icons that we can all add to. I have several links as placeholders for now, til they are migrated. Please let me know what you think. Thx!

cc @sez11a

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Pending update based on https://issues.liferay.com/browse/LRDOCS-7510

**Comment by mwilliams2014** [comment]
Updated and file extensions renamed to `.md`

**Comment by mwilliams2014** [comment]
Updating to match proper formatting for filenames and images

**Comment by mwilliams2014** [comment]
Updated

**Comment by jrhoun** [comment]
Reviewing this pull now.

**Comment by jrhoun** [comment]
Hi @mwilliams2014 going to close this out for now as you review my pull here: https://github.com/mwilliams2014/liferay-learn/pull/1

**Comment by mwilliams2014** [comment]
Resent https://github.com/jrhoun/liferay-learn/pull/87

**Pull request closed without merging**
