### PR TITLE
LRDOCS-8730 Sharing Forms and Form Reports Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8730
https://issues.liferay.com/browse/LRDOCS-8707

@rbohl

- LRDOCS-8730 update sharing forms
- LRDOCS-8730 form metrics reports
- LRDOCS-8730 add rich text, color, and image field types to the reference doc
- LRDOCS-8730 add my annoyance to the git history
- LRDOCS-8730 reformat field types reference (remove useless table) and add new fields
- LRDOCS-8730 guest user uploads not allowed
- LRDOCS-8730 couple more things, images
- LRDOCS-8730 proofreading edits
- LRDOCS-8707, document the Field Name > Field ID issue, and the coming Field Reference
- LRDOCS-8730 rename Form Metrics > Form Reports
- LRDOCS-8730 sme edits
- LRDOCS-8730 add supported image file types
- LRDOCS-8730 Wordsmithing.

### CODE REVIEW

**Comment by rbohl** [comment]
@jrhoun if you can prioritize this when you get in, it will help me get moving on the Forms [7.3-FP1 feature](https://issues.liferay.com/browse/LRDOCS-8800) I need to document. Thanks!

**Comment by jrhoun** [comment]
Yup @rbohl, I'm on it this morning.

**Comment by jrhoun** [comment]
Merged. Thanks.

**Comment by rbohl** [comment]
Thanks for the speed, @jrhoun and @sez11a !

**Pull request closed without merging**
