### PR TITLE
LRDOCS-8150 Workflow XML Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8150

@justinchoi001 Though I'm pushing this forward to JR, I have feedback for you, which I'll send via email.

### CODE REVIEW

**Comment by jrhoun** [comment]
FYI @justinchoi001 in this commit 8eef6c0065df78ba03822e0c8641aefb7202ba14 - you deleted all of the screenshots for the article `Using Data Providers to Populate Form Options` -- and there is no replacement, so I am assuming that was done on accident. I'm going to bring those files back. Please correct me if those screenshots were intended to be deleted.

**Comment by justinchoi001** [comment]
Hi @jrhoun, yes, I made a mistake in accidentally deleting those files. Please include them and all the screenshots. Thanks.

**Comment by jrhoun** [comment]
Hey @sez11a - first, hope you're well. second - I'm a little concerned about where we stored the `.xml` workflow definitions here -- they aren't in a `/resources` dir. I'm considering moving those files into a dir that matches existing patterns: `/article-name/resources/abc.xml`. What do you think?

**Comment by sez11a** [comment]
@jrhoun Ah, nuts. I meant to do that as a last step before forwarding to you, but I'd taken so long to wordsmith/rewrite this that I think I got overexcited about pushing it forward toward publication and forgot to do that. Thanks for catching it!

**Comment by jrhoun** [comment]
Merged. Thanks. See my changes: https://github.com/liferay/liferay-learn/compare/208e2cb65ac1f02c423369dd00af0a8b4fc0ac2c%5E...87ddc95dfb961718df6a6cb2034da487ad3fe685

**Pull request closed without merging**
