### PR TITLE
Analytics Cloud Documentation from November 2020

### PR DESCRIPTION
**Pull request by bbsuh**
Hi JR,

I'm sending this pull request to you containing Japanese translations of Analytics Cloud docs from November 2020.

Thanks!

### CODE REVIEW

**Comment by jrhoun** [comment]
Thanks @bbsuh . CC'ing @mtokudome who is the primary TW for the AC team. @mtokudome, can you test this pull out and check the build for any rendering issues? Let me know if you need clarification/assistance with this. Thanks!

**Comment by mtokudome** [comment]
Hi, I took a look at this and have some comments:

- So a number of changes (i.e. new articles or updates) have gone in since Nov 2020. For example - Multi-Factor Authentication, removal of OAuth connection, Workspace timezone, etc. I'm guessing the AC product team will have thoughts about wanting to get those articles included.
- Some smaller details. There seems to be some inconsistency with terms using Japanese or English. For example, I see "Web Content" in some places but probably should consistently be "Webコンテンツ". Same thing with "paths" vs "パス". Another one is "segment" vs "セグメント". "個人" vs "ユーザー" might be another one to double check.
- Accounts.md has "[ ]" that need to be removed.
- Other than that, I looked at each page and they all seem to be rendering fine.

**Comment by holatuwol** [comment]
@mtokudome

> I'm guessing the AC product team will have thoughts about wanting to get those articles included.

Translation of documents from mid-March 2021 is in progress, so those newer documents will be included in the next pull request when that batch has completed.

> There seems to be some inconsistency with terms using Japanese or English.

Sure, we'll let the translation team know about the inconsistency for web content, paths, segment, and user so we can add those terms to the glossary for the next batch.

> Accounts.md has "[ ]" that need to be removed

Making sure, are you referring to the `[]` in the title?

**Comment by jrhoun** [comment]
Superseded by https://github.com/liferay/liferay-learn/pull/169

**Pull request closed without merging**
