### PR TITLE
search 7.x | similar results scope selector | LRDOCS-10232

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-10232
cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
We should indicate which update includes the changes

**Comment by lipusz** [comment]
There is no indication anywhere in learn.liferay.com which liferay dxp versions the articles refer to, so I prefer being specific when it comes to documenting enhancements of existing features.

It'll be in the DXP 7.4 U15 cut.

>We could specify the 7.3 SP/FP though

Yes, we'll once it's backported.

**Comment by rbohl** [comment]
https://learn.liferay.com/dxp/latest/en/index.html
> Welcome to the official documentation for the latest versions (7.3 and 7.4+) of Liferay DXP and Liferay Portal!

**Comment by jrhoun** [comment]
Merged. Thanks.

**Comment by lipusz** [comment]
As it's not backported to 7.3.x yet, I'd like to indicate the fixed version for 7.4 @rbohl

**Comment by rbohl** [comment]
https://github.com/jrhoun/liferay-learn/pull/1412

**Pull request closed without merging**
