### PR TITLE
Fundamentals: New articles and placeholders

### PR DESCRIPTION
**Pull request by jhinkey**
Hi JR,

I've revamped the module/osgi/services content into three articles at the start of Fundamentals. I want to get these placeholders in place for the code and article content, which are coming in a variety of atomic code and article branches that may take a long time to get to you.

So if I can get this in, then I can rebase those branches right away to include these common placeholders. Does that make sense? Ping me if you want to discuss. Thanks!

Jim

### CODE REVIEW

**Comment by jhinkey** [comment]
Scratch that. Since the PRs are already out there, I'll run into more conflicts with this. Thanks anyway.

**Comment by jhinkey** [comment]
I'm reopening this as having the article placeholders present allows me to use cross references in the individual article PRs. :-)

**Comment by jrhoun** [comment]
Just started reviewing!

**Comment by jrhoun** [comment]
Merged. Thanks!

To simplify our file structure, I'm trying to slowly remove `README.rst`s as we can accomplish what they are doing by adding their content to the "section" rsts themselves -- eliminating an additional file to have to keep up to date. See https://github.com/liferay/liferay-learn/commit/83ea68ea4e79b16f1c8dabf476eea9088c48d331.

**Pull request closed without merging**
