### PR TITLE
LRDOCS-9368 Sites Dashboard Update

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-9368

Forwarding with no changes. 

@mtokudome If you have minor changes like this, please send them directly to @jrhoun.

### CODE REVIEW

**Comment by jrhoun** [comment]
Hey @mtokudome @sez11a -

When I pulled this PR down and rebased on master I noticed that it includes commits that have not yet been merged into master:

image

Specifically the commits from James -- they seem relate to other articles. Can this PR be re-sent with just the commits for Sites Dashboard updates?

**Comment by mtokudome** [comment]
Sure, I'll send you a new PR

**Comment by mtokudome** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/1060

**Comment by jrhoun** [comment]
Closing per @mtokudome

**Pull request closed without merging**
