### PR TITLE
Refer to as Liferay DXP and change version to DXP 7.2 SP2+

### PR DESCRIPTION
**Pull request by mwilliams2014**
@jrhoun These are changes for the sponsored dev features being released in DXP 7.2 SP2 today. Please merge as soon as you can. Thanks! cc @rbohl

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jrhoun 7.2 SP2+ has been pushed to a release date for 3/17/20, so we don't need to rush this at this time.

**Comment by jrhoun** [comment]
Merged. See https://github.com/liferay/liferay-learn/commit/2abb0343aca34c11dcc9c59d96ea29e9f73c8f33

Thank you!

**Comment by mwilliams2014** [comment]
Thanks @jrhoun ! As I noted, this has been pushed to a release date for 3/17/20. I'll add a proper intro before then.

**Comment by mwilliams2014** [comment]
@jrhoun 7.2 SP2+ has now been pushed to March 31st. So we don't want to publish this info til then. Thanks!

**Pull request closed without merging**
