### PR TITLE
Upgrade stuff

### PR DESCRIPTION
**Pull request by Alec-Shay**
Sending the whole upgrade with all the revisions from when I last went over these with you.

A few notes from these changes:

- **For the intro to upgrade article:** I (or we?) thought maybe it would also be good to add some references to articles talking about migrating to a supported DB (or DB version) in the new "planning" section. However, I didn't turn up good existing articles for this purpose after a quick search, so I left that out for now.
- **For the application server article:** for the same reason as above, I didn't add a reference to an article listing recommended database drivers at the note that talks about that. Something like this should exist somewhere, though, definitely.
- **Also for the application server article:** I made a table making it more clear how the changed property defaults actually changed, but as I was cross-checking to verify the values between verifying versions of Liferay (between 7.2 and as far back as 6.2), I noticed several mistakes or points of confusion. In particular, some of the "changed" properties were actually removed/turned into OSGi configs (which I added to the "removed" list instead, but it feels a bit weird to me because we don't explicitly say most of the configs that were migrated to OSGi configs), and some others actually don't seem to have been changed at all (as far as I could tell, they were introduced in 7.0, and they have stayed the same all the way until 7.2.x):

```properties
discussion.comments.format
discussion.max.comments
editor.wysiwyg.portal-web.docroot.html.taglib.ui.discussion.jsp
```

The existing documentation shows the "old" values, but I really have no idea where those values came from, since all the versions I'm looking at either don't have the property at all or just have the new value. I removed these properties from the list for now since it seems like the information is wrong, but if possible I would really like to know where these actually came from, and what the methodology they were using for finding all these changed properties is, in case I'm missing something important.

When you have the time, please let me know of any concerns or thoughts you may have about all this (whether it's related to any of these points or something else we should take a look at). Thanks in advance.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@jhinkey If you might also want to take a look at these (restructuring and reworking of the existing upgrade docs)

**Comment by jhinkey** [comment]
@Alec-Shay I think the Intro should mention the upgrade paths up front. Maybe like this ...

## Upgrade Paths

Here are the installation upgrade paths:

| Upgrade Path                            | Description |
| --------------------------------------- | ----------- |
| Liferay Portal 5.x and 6.0.x &rarr; Liferay Portal 6.2 &rarr; Liferay DXP 7.2 | Support life ended for Liferay Portal 5.0, 5.1, 5.2, and 6.0 |
| Liferay Portal 6.1.x &rarr; DXP/Portal 7.1 &rarr; DXP 7.2 | Support life ended for Liferay Portal 6.1 |
| Liferay Portal 6.2+ &rarr; DXP 7.2      |             |
| Liferay DXP/Portal 7.0+ &rarr; DXP 7.2  |             |

If you're upgrading to Liferay Portal 6.2, follow the [Liferay Portal 6.2 upgrade instructions](https://help.liferay.com/hc/en-us/articles/360017903232-Upgrading-Liferay) first. 

If you're upgrading from Liferay Portal 6.1 to Liferay DXP/Portal 7.1, you can use these instructions.

**Comment by Alec-Shay** [comment]
Closing since we have changes after discussion with @jhinkey. Will send a new one soon (maybe not just yet because there may be more edits coming up, pending more feedback from Alberto et al.).

For reference this is with the latest changes at this time: https://github.com/Alec-Shay/liferay-learn/commits/upgrade-edits

**Comment by Alec-Shay** [comment]
Re-sent to: https://github.com/jrhoun/liferay-learn/pull/58

**Pull request closed without merging**
