### PR TITLE
LRDOCS-10072 Japanese Translations Update for Commerce

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LRDOCS-10072

/cc @sophia6497

We're breaking up the latest update into smaller batches to make it easier to manage on the Japanese side, so a few more pull requests will be sent using the same LRDOCS ticket.

I found a broken link in the English version of the article while validating the Japanese, so I'm also including it in this pull request. You can see it on the live site here (try clicking on the List link):

https://learn.liferay.com/commerce/latest/en/creating-store-content/commerce_storefront_pages.html

### CODE REVIEW

**Comment by holatuwol** [comment]
Pull request wasn't closed, so I've added the developer guide folder updates to this pull request.

**Comment by holatuwol** [comment]
Pull request wasn't closed, so I've added the installation and upgrades folder updates to this pull request.

**Comment by holatuwol** [comment]
Pull request wasn't closed, so I've added the managing a catalog folder updates to this pull request.

**Comment by holatuwol** [comment]
Pull request hasn't started review, so I've added the "orders and fulfillment" folder updates to this pull request.

**Comment by holatuwol** [comment]
Pull request hasn't started review, so I've added the following folders to this pull request:

* promoting-products
* starting-a-store
* store-administration

This also includes some fixes for broken EN links that were found while checking the JA links.

**Comment by holatuwol** [comment]
Remaining documentation added to the pull request.

**Comment by holatuwol** [comment]
Added anchor tags so that links within EN documentation also work with JA documentation where all of the headings have a different auto-generated ID.

**Comment by jrhoun** [comment]
Merged. 

Thanks for your work on this @holatuwol . The anchor tag solution seems...rough but I also can't think of an alternative. Did you have to add those by hand?

**Comment by holatuwol** [comment]
@jrhoun No, they were added via script, so it's no extra work.

**Pull request closed without merging**
