### PR TITLE
Japanese Translation for DXP Cloud documentation

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by jrhoun** [comment]
@alec-shay can you take a look at this and give me a thumbs up if it looks ok to you? Thanks

**Comment by Alec-Shay** [comment]
@jrhoun I think it mostly looks okay (as far as I can tell), except something funky is going on with this line, and it breaks the DXPC landing cards: https://github.com/jrhoun/liferay-learn/pull/934/files#diff-fefa200c1863c928f985b2563114e1a7e7618271dec8d036d9486aed1930218eR79

**Comment by holatuwol** [comment]
Updated!

**Comment by jrhoun** [comment]
Merged. Thanks.

**Pull request closed without merging**
