### PR TITLE
[DXP Cloud] LRODOCS-9388 Add new article explaining log structure

### PR DESCRIPTION
**Pull request by Alec-Shay**
See: https://issues.liferay.com/browse/LRDOCS-9388

This adds a new article breaking down the components giving contextual information in log messages, as per request from the DXP-C product team.

### CODE REVIEW

**Comment by jrhoun** [comment]
@Alec-Shay One thought that came to mind as I was reviewing. How does the new article (`reading-logs-in-dxp-cloud`) relate to an older article that is published, `log-management`? I assume we should probably add a cross reference in there, but is there some duplication in the information too?

**Comment by Alec-Shay** [comment]
@jrhoun Hmmm... I guess there is some overlap. The "how to access" parts may be some duplication, and I guess you could also argue that the "Types of Logs" may belong more in this new one too... though I'm not sure about that. Cross references would make sense at the very least, though I'm a bit on the fence as to how best to address the overlaps

**Comment by jrhoun** [comment]
Maybe just merge all the content that you're proposing into the `log-management` article. IMO

**Comment by jrhoun** [comment]
IMO, I'd still keep it where it is - both the article naming and organization - mostly informed by not wanting to break links. That being said, if you want to move/rename I'm open to it, just have to be cognizant of the impact.

**Comment by jrhoun** [comment]
Merged. Thanks. ba85b148813f2e022f403f1e3606ee79b6cc492c

**Pull request closed without merging**
