### PR TITLE
LRDOCS-9727 Implement and test sphinx-design addon

### PR DESCRIPTION
**Pull request by rdai10**
https://issues.liferay.com/browse/LRDOCS-9727

@jrhoun 
After playing around with sphinx-design, my impression is that while it's nice to add UI components in the docs themselves, it couples the markdown content with the sphinx-design syntax. Then syntax itself is a little finicky in my experience and prone to error. In order to replace the current vue.js based landing page cards, the site maintainer would need to learn both the md and rst syntax and apply them correctly depending on where in the folder structure the landing page is. Even then, it doesn't seem to offer enough flexibility to completely replicate the current landing pages as is.

Given this [comment](https://issues.liferay.com/browse/LRDOCS-8828?focusedCommentId=2392689&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2392689), I'm not sure what the likelihood of using sphinx-design for [dropdowns](https://sphinx-design.readthedocs.io/en/sbt-theme/dropdowns.html) is, so I didn't explore it.

However, I do think you could still leverage sphinx-design for display badges, unless there are other extensions available. They seem to be fairly straightforward and easy to apply. Although when the Design department weighs in on the appropriate colors to use for each of the [possible badge options](https://issues.liferay.com/browse/LRDOCS-8821), additional styling will be needed to override the default.

Here's an example:
image

### CODE REVIEW

**Comment by rdai10** [comment]
@jrhoun 

Following our conversation, I tried using md syntax to add links as card content. They don't seem to be parsed properly. However once the text and link are coerced as buttons, they then display properly in the card.

Here's a screenshot, you can play around with the content in [cdbfe57](https://github.com/jrhoun/liferay-learn/pull/1386/commits/cdbfe57c9fd7dea199da84a5916606a7e6376103). It would seem to me that this would be a deal breaker.

image

Let me know what your thoughts are.

Thanks!

**Comment by rdai10** [comment]
@jrhoun 
Here's the sphinx-cards styled to look like the original landing page.

There are two things that need alternative solutions:

1. With just sphinx-design, the cards will no longer hide more than 3 titles with the ... icon where upon clicking will expand to show all titles.
2. The layout of the page cannot be altered to full screen and would follow the same 80-20 layout of a typical documentations page.

Here's a comparison:
Sphinx-Design:
image
Vue-based:
image

**Comment by jrhoun** [comment]
Merged. Thank you @rdai10 and best wishes to you for everything you do going forward! ❤️

**Comment by rdai10** [comment]
Thanks @jrhoun !

**Pull request closed without merging**
