### PR TITLE
LRDOCS-7552 port Site Settings docs to liferay-learn

### PR DESCRIPTION
**Pull request by mwilliams2014**
Leaving Site Localization out of this PR. Still trying to determine what that entails exactly. There is a bit of info on Localization: The Languages Site Setting and a separate article on Modifying Localizable Site Setting Fields, but there's not enough info to justify its own section.

### CODE REVIEW

**Comment by jrhoun** [comment]
Hi @mwilliams2014 - I've just started reviewing this. Structurally - I think it needs quite a bit of work. I'm not yet a big fan of how its organized. I'm working on a mindmap to illustrate how I'd rather see this re-envisioned - but the general trust of it is:

1. Provide a clearer overview and center the reader on what it is they're looking at and where it is in the product. (When I initially read `Configuring General Site Settings` - I was very confused because I read the intro paragraph and then the next header was "Details". "Details? For what? Where am I in the product again?")

2. Try and provide articles that more driven to solve common problems/use cases. Analytics is one example. On one hand we provide a whole article dedicated to showing how to add a _new_ analytics service as an option - which is good - but how common is that? (I don't know). But on the other hand we don't actually really provide a thorough how-to walkthrough on setting up google analytics (which is an analytics service we already have), and yes the article can just say, fill in the information in the boxes - but we probably could go further and just do a full walk through and have an article titled, "Configuring Analytics for a Site" - where it shows us putting the information in, saving it, testing it, and showing what it looks like when it works. IMO that's a pattern that we should repeat for settings that we think might be particularly relevant to users.

My mind map will just be a draft/suggestion on how to reorganize things along the lines i've laid out above.

**Comment by jrhoun** [comment]
Ok - this is how the section is (more or less) currently laid out in this pull:

image

Here's my modeling out of how I would rather see it organized over a couple screenshots:

1)
image

2) 
image

===

Organizing this way does a couple things. It leaves a top level overview that has a primary purpose to acquaint someone with the whole of "Site Settings" - including where to find it. It also provides a Site Settings UI Reference - which would be a combination of two articles that this pull currently has (Configuring Site Settings and Advanced Site Settings) - this keeps an article together that presents the information in a reference style - organized how it is presented in the UI - which is what _some_ users expect.

This also organizes the rest of the site settings articles into more topical sections that can help readers (particularly those new to working around liferay) get to what they're trying to find faster, rather than digging through other settings they aren't interested in.

CC @sez11a - tagging you as an FYI and in case you have input on the feedback i'm giving @mwilliams2014 .

**Comment by jrhoun** [comment]
Sorry that it took me so long to provide this feedback @mwilliams2014 ! But I hope that this helps and makes sense, closing this for now and look forward to revisiting it soon.

**Comment by mwilliams2014** [comment]
Thanks for the thorough feedback @jrhoun ! I'll make the changes as soon as I can.

**Pull request closed without merging**
