### PR TITLE
Mail server configuration (Rebased)

### PR DESCRIPTION
**Pull request by Alec-Shay**
Re-sent from https://github.com/jrhoun/liferay-learn/pull/168. Mail server configuration articles (originally by @justinchoi001) rebased to fix original conflicts, and with a few more minor edits. Also refactored the article locations because the folder they were originally written in has been removed since the PR was sent.

### CODE REVIEW

**Comment by jhinkey** [comment]
@Alec-Shay - Would you track these articles in this ticket? https://issues.liferay.com/browse/LRDOCS-7714

**Comment by Alec-Shay** [comment]
@jhinkey Is that a workflow thing for LRDOCS tickets? I'm not 100% sure what you're asking me to do.

**Comment by jhinkey** [comment]
Yes in a way. Since several of us are involved with the docs in or linked in Setting Up Liferay DXP, assigning yourself the tickets you are working on or plan to work on helps us avoid multiple people working on the same docs.

**Comment by jhinkey** [comment]
So for example, since you sent this PR to JR, if you plan on handling its review requests you should assign the mail ticket to yourself. Otherwise, ask Justin to assign himself.

**Comment by jrhoun** [comment]
I pushed this up with quite a few changes. See https://github.com/liferay/liferay-learn/commit/3e7699671cdfec85306f2547536605b08d071151

**Pull request closed without merging**
