### PR TITLE
LRDOCS-9582 remove references to recommonmark

### PR DESCRIPTION
**Pull request by rdai10**
https://issues.liferay.com/browse/LRDOCS-9582

When I did a search against the existing docs, most of the current syntax for admonition already matches MyST syntax, I updated the few places that slipped through the cracks. However, there are a handful of places for the Japanese translations. I'm not familiar with the translation process, should these places be updated manually or is there some kind of process that should be run to update the translated pages?

Note, MyST supports md flavored tables, additional table plugin has been removed. However writers can align tables cells [following this guide](https://github.github.com/gfm/#tables-extension-).

**before change:**
image

**after removing sphinx markdown table:**
image

**after [54bfdd6](https://github.com/jrhoun/liferay-learn/pull/1377/commits/54bfdd60a4a40f2b0230f28ab3e0152a04a5ca7d)**
Note, none of the Japanese translated pages are touched.
image

### CODE REVIEW

**Comment by jrhoun** [comment]
Noticed an odd regression introduced here:
image

What do you think? I tested this on Firefox and Chrome in incognito.

**Comment by rdai10** [comment]
Hmm good catch, for some reason, the copy button is broken. I'll have to take a look.

**Comment by jrhoun** [comment]
> In the meantime, do we manually update the japanese version of the docs? Or is there some kind of process that will take the current state of the english docs and apply those to the japanese docs?

AFAIK right now we (referring to Tech Writers) only touch the JA docs when we move articles around on the EN side, the JA team periodically syncs the translations over and goes through a process to translate vis-a-vie crowdin.

**Comment by rdai10** [comment]
Sounds good, I'll leave the few places where old admonition syntax was used in the Japanese version of the docs as is.

**Comment by rdai10** [comment]
@jrhoun issue fixed, ready for review.

**Comment by jrhoun** [comment]
Merged. Thanks!

**Pull request closed without merging**
