### PR TITLE
LRDOCS-8731 Commerce Tutorial Updates: Update commerce tutorials to code changes and to use Liferay 7.3

### PR DESCRIPTION
**Pull request by jhinkey**
This is the first installment of updates for parent ticket LRDOCS-8597.

This child ticket https://issues.liferay.com/browse/LRDOCS-8731 focuses on the Commerce tutorials. Here's a summary of the changes:

- Sync with the example code changes.
- Base the UI steps on Liferay 7.3 and note Commerce 2.1- steps
- Start a Liferay 7.3 docker image
- Update the screenshots to accommodate Liferay 7.3 and the example code changes.
- Update the example source file paths to include **resources**/liferay-xxxx.zip/
- Update the Commerce source code links to the locations in liferay-portal repo, instead of the old commerce repo.

cc @Alec-Shay

### CODE REVIEW

**Comment by jrhoun** [comment]
@alec-shay can you take a look at this before I merge?

**Comment by Alec-Shay** [comment]
Hey @jhinkey,

Thanks for these changes, I can see there are quite a few issues (functionally and style-wise) being fixed here.

I think the changes look good to me. The one thing though that I see (that maybe is an overlooked detail?) is that the word "products" is broadly being changed to "items," but I think that maybe creates some inconsistencies with how they are termed in the tutorial text (at least it would probably make sense if the term was consistent I think). For example on this line: https://github.com/jrhoun/liferay-learn/pull/824/commits/f1ebef5b8132f52e6a7f79bebf0551bb972a8471#diff-7b77aa37051d2a0ea26b0186987255424f61a0ed037090a4cd02ab946813cb86R221

**Comment by jhinkey** [comment]
@Alec-Shay I changed the term from "products" to "items" because the discount is based on the quantity of products regardless of product type. The other discounts for example focus on product type (product), whereas this one does not. I hope that makes sense. :-)

**Comment by jhinkey** [comment]
@jrhoun (cc @Alec-Shay) This seems ready to merge. I'd prefer that this gets merged before we address any other issues in these tutorials, such as https://issues.liferay.com/browse/LRDOCS-8793.

**Comment by Alec-Shay** [comment]
> @Alec-Shay I changed the term from "products" to "items" because the discount is based on the quantity of products regardless of product type. The other discounts for example focus on product type (product), whereas this one does not. I hope that makes sense. :-)

(Thought I responded to this but realized I never did, apologies)
That does make sense to me!

**Comment by jrhoun** [comment]
Merged. Thanks!

**Pull request closed without merging**
