### PR TITLE
LRDOCS-7542 Page Fragments Dev Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
We went back and forth a few times on this, but I think now it's in good shape. Great job, @mwilliams2014!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Yay! Glad to hear it @sez11a  :-)

**Comment by jrhoun** [comment]
Hey ya'll. I am not merging this particular pull - primarily because the samples' sources aren't included and so we're not following the convention that Brian laid out. Specifically to have the tutorial sources in a folder following the naming convention `/a1b2.zip/`. I also left a comment about one of the tutorials where there's a separate build step, and then a separate deploy step to copy the sample to the docker container. I believe there are examples of those two commands being condensed into a single gradle command - we should follow that pattern if possible. I pushed all my changes up to https://github.com/jrhoun/liferay-learn/commits/pr-509 @mwilliams2014 so you can get everything I updated. Let me know if you guys have any questions!

**Comment by mwilliams2014** [comment]
Thanks @jrhoun ! I'll make the changes as we discussed and send back to you to verify everything looks good.

**Comment by mwilliams2014** [comment]
@jrhoun Where will the zipped files be hosted on the Site?

**Comment by jrhoun** [comment]
See https://learn.liferay.com/dxp/7.x/en/using-search/developer-guide/writing-a-similar-results-contributor.html for an example. In that case the `/liferay-r1s1` was zipped up at site build time, then uploaded here: https://learn.liferay.com/dxp/7.x/en/using-search/developer-guide/liferay-r1s1.zip

**Comment by sez11a** [comment]
Ugh; can't believe I missed that. I didn't even look at the code. @mwilliams2014 I'm guessing you'll need to update this one also (plus it's merge-conflicted): https://github.com/sez11a/liferay-learn/pull/56

**Comment by mwilliams2014** [comment]
Yep @sez11a . I wasn't aware that the script zips the file :-) I'll take care of that one in a bit after I make these updates and I'll (hopefully) resolve the merge conflict.

**Pull request closed without merging**
