### PR TITLE
search 7.3 | upgrading elasticsearch | wordsmithed

### PR DESCRIPTION
**Pull request by rbohl**
cc @sez11a I had force pushed one commit into the branch you'd been wordsmithing, and it didn't make it in here. So I've cherry-picked it onto your branch. Can we close https://github.com/jrhoun/liferay-learn/pull/839 in favor of this?

https://issues.liferay.com/browse/LRDOCS-7788

cc @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
**TODO**: https://github.com/rbohl/liferay-learn/blob/search_7.3_upgrading-elasticsearch_LRDOCS-7788/docs/dxp/7.x/en/installation-and-upgrades/upgrading-liferay/upgrade-basics/post-upgrade-considerations.md is not mentioning the additional reindex need for Workflow Metrics indexes.

**Comment by lipusz** [comment]
**TODO2**: Add a general note that if the `indexNamePrefix` is configured differently from the default (`liferay-`) on the pre-upgrade environment, when upgrading from DXP 7.2 the ES7 connector in DXP 7.3 must be configured to use the same prefix.

**Comment by lipusz** [comment]
Created https://issues.liferay.com/browse/LRDOCS-8759 for these.

**Comment by lipusz** [comment]
@rbohl Looks like it was not merged so I guess need to resend the changes. :-/

**Comment by rbohl** [comment]
Good catch @lipusz, I'll cherry-pick the dangling commit into a new branch and re-send.

**Pull request closed without merging**
