### PR TITLE
LRDOCS-8524 Update 7.3 Defaults Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-8524

@jhinkey

- LRDOCS-8524 alphabetical order
- LRDOCS-8524 update 7.3 default setting changes
- LRDOCS-8524 Use consistent title pattern "blah blah in x.x"
- LRDOCS-8524 Wordsmithing.

### CODE REVIEW

**Comment by jrhoun** [comment]
So. On paper this article looks fine. But rendered it doesn't look so hot:

image

(mobile)

image

I'm kinda torn on whether to merge this in its semi-broken state -- or to either:

**Comment by jhinkey** [comment]
I think a) is the best option. Since the content isn't fixed-width, a style should be able to wrap it in each column. Other tables would benefit from the style too.

**Comment by jrhoun** [comment]
Ok, I'll push this forward, but make a note about a future site improvement for table rendering.

**Comment by jrhoun** [comment]
Merged. Thanks.

**Pull request closed without merging**
