### PR TITLE
Script migrates liferay-docs articles to liferay-learn

### PR DESCRIPTION
**Pull request by jhinkey**
The `migrate.py` script converts the article to the new Markdown format, renames it with the .md suffix, and optionally copies the converted article and its images to a destination folder (e.g., in `liferay-learn`)

Usage: migrate.py article [dest_folder]

IMPORTANT: Run this script in the source article's folder in `liferay-docs` so that the script can access the image files using the paths in the article. 

`dest_folder`: Specify the article's new location in `liferay-learn`. If no `dest_folder` is specified, the article is converted to `[current_folder]/[article].md` and the article images are copied to `[current_folder]/images/`. 

Example:
C:\git\liferay-docs\en\user\articles\05-setting-up\01-system-settings>migrate.py 01-system-settings.markdown \git\liferay-learn\docs\dxp\7.2.x\en\user-and-system-management\03-system-management

### CODE REVIEW

**Comment by rbohl** [comment]
It would be nice if this can be merged soon. I can just grab it locally for now, but I'd rather it was under version control so we can all contribute improvements.

**Comment by jhinkey** [comment]
@jrhoun - Yes, please merge this soon. It's my early Christmas present to @rbohl ... and the rest of the KM/Evangelism team :-D

**Comment by jhinkey** [comment]
@rbohl added logic for migrating sidebars too! :-D

**Comment by jhinkey** [comment]
@jrhoun Can you prioritize merging these improvements to the migrate command? That way, folks can get them by merging with upstream master. :-D

**Comment by jrhoun** [comment]
Merged.

**Pull request closed without merging**
