### PR TITLE
Search 7.3 | Using Search Configuring Search | LRDOCS-7674

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOS-7674, I'm still clueless with these RST files. Please advise if you'd like me to do something about them.

### CODE REVIEW

**Comment by jrhoun** [comment]
> https://issues.liferay.com/browse/LRDOS-7674, I'm still clueless with these RST files. Please advise if you'd like me to do something about them.

They suck. Really. After this week I'm probably going to write something up about them for the docs standards.

**Comment by jrhoun** [comment]
My initial impression is a 👎 . The "Intro" `Using Search` article feels long, has some lengthy lists, and overall doesn't leave me with an impression of what's possible with Search. I say this as someone who basically has very minimal understanding of Search and Liferay.

For an intro I'd hope to see something that says something to the effect of:
```
# Using Search

Liferay uses an embedded instance of Elasticsearch to power search throughout the system. We recommend that users who are going to production install a standalone elasticsearch instance for optimal system and search performance.

Liferay's search functionality includes:
[borrowed from https://webhelp.episerver.com/latest/en/cms-edit/search-website.htm]
* Full-text search features.
* Indexing of all content types: blogs, documents, web content, etc.
* Event-driven indexing, meaning instant updating of the index and search results.
* Search results filtered by roles and permissions.
* Search suggestions
* Supports basic boolean operators like AND, OR, NOT, + , - and *.

## Search Widgets

The following widgets come out-of-the-box and can be used to quickly build out a fully functional search page that supports rich results, facets, fancy things...

| widget | usage |
| --- | --- |
| blah | blah |

Here's a link to an article that shows you how to build a search results page.

## Search Configuration and Administration

There are several ways to configure how search works and how it indexes content. x, y, and z.

```

I drew inspiration from:

* https://docs.adobe.com/content/help/en/experience-manager-65/assets/using/search-assets.html
  * I really like the organizational scheme for ^ - searching for stuff, configuring stuff, messing with search results
* https://webhelp.episerver.com/latest/en/cms-edit/search-website.htm - this intro was nice
* https://world.episerver.com/documentation/developer-guides/CMS/search/

**Comment by jrhoun** [comment]
Closing this for now.

**Comment by rbohl** [comment]
@jrhoun 
Should I leave out the dev guide intro? Didn't see you mention that part, but I was assuming this article should introduce the dev guide and the user guide.
https://github.com/jrhoun/liferay-learn/pull/247/files#diff-09f28e79576e30f5d955358eb7b0c51cR42

**Pull request closed without merging**
