### PR TITLE
search 7.x | content dashboard not supported on solr | LRDOCS-10459

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-10459
cc @lipusz

### CODE REVIEW

**Comment by jrhoun** [comment]
Merged. Thanks.

**Comment by lipusz** [comment]
I'm sending this song to Russ :stuck_out_tongue_closed_eyes: https://www.youtube.com/watch?v=yyDUC1LUXSU

**Comment by lipusz** [comment]
Ah, wrong PR :-D

**Comment by lipusz** [comment]
But I think you guys know the context :innocent:

**Pull request closed without merging**
