### PR TITLE
Upgrading Liferay DXP

### PR DESCRIPTION
**Pull request by jhinkey**
Hi JR.
Thanks for your patience with this. I've added _A Simple DXP Upgrade_ and refactored the _Introduction to Upgrading Liferay DXP_. The other articles are reorganized under `advanced-upgrade-topics` and `reference`.

I refactored the articles to focus on the reader's new DXP version instead of DXP 7.2 specifically.

https://issues.liferay.com/browse/LRDOCS-7640
https://issues.liferay.com/browse/LRDOCS-7600

cc/ @Alec-Shay

Jim

### CODE REVIEW

**Comment by jrhoun** [comment]
I've started reviewing this now @jhinkey. My initial impression though is that it doesn't quite hit the mark and even the "A Simple DXP Upgrade" feels too cumbersome. I'm going to do some work on this and I'll send a pull to your `upgrading-liferay-dxp` branch for your consideration.

**Comment by jhinkey** [comment]
Sounds good 👍

**Comment by jrhoun** [comment]
See my pull w/ updates/edits: https://github.com/jhinkey/liferay-learn/pull/6

**Comment by jrhoun** [comment]
Closing this for now since I sent my revisions in jhinkey#6

**Pull request closed without merging**
