### PR TITLE
SSO Docs without formatting in alt text

### PR DESCRIPTION
**Pull request by sez11a**
Here are the SSO docs, ported to Liferay Learn.

I was going to fix the file names and the toc files, but realized I didn't know how to do that, and I need to go back and figure out how they work.

### CODE REVIEW

**Comment by sez11a** [comment]
Hey @jrhoun this doesn't look like it got merged. Did you close it by mistake?

**Comment by jrhoun** [comment]
Not even sure how it got closed to begin with.

**Comment by jrhoun** [comment]
Just started reviewing.

**Comment by jrhoun** [comment]
Merged here: https://github.com/liferay/liferay-learn/compare/eacaa4f456b6222ead34b0236cd5b51f7bea5cf3...c618bb10b012bc662d16ee584a64a66dc574e699

Basically reviewed, edited, merged everything with the exception of SAML materials - which I left as placeholders for now until we can circle back to it at a later time.

**Pull request closed without merging**
