### PR TITLE
LRDOCS-7848 LRDOCS-7716 Tuning Liferay and the JVM Wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/LRDOCS-7848
https://issues.liferay.com/browse/LRDOCS-7716

@jhinkey

- LRDOCS-7634 the conventional file name is portal-developer.properties
- LRDOCS-7848 add tuning-liferay.md and the placeholder tuning-your-jvm.md
- LRDOCS-7848 mention NIO connectors
- LRDOCS-7848 use the portal tag token
- LRDOCS-7716 set heap to 2560m
- LRDOCS-7716 rewrite tuning-your-jvm.md
- LRDOCS-7848 Wordsmithing.
- LRDOCS-7716 Wordsmithing.

### CODE REVIEW

**Comment by jhinkey** [comment]
Sorry guys, there are some new recommendations for connection pool tuning. I'd like to make those changes first.

**Comment by jhinkey** [comment]
@sez11a - This PR has the Oracle JVM clarification and the Hikari CP connection pool example.

https://github.com/sez11a/liferay-learn/pull/316

**Comment by jhinkey** [comment]
Hey guys (@jrhoun @sez11a ). This branch is now merge conflicted because of the changes in Setting Up Liferay--I expected the merge conflict. 

I have important updates for these two articles (clarification about the JVM settings used and an example HikariCP db connection pool configuration) AND I've rebased on master, which needs to be done to resolve the conflict.

Can you guys close this PR and can we continue work via the PR I sent Rich? https://github.com/sez11a/liferay-learn/pull/350

**Comment by jrhoun** [comment]
Closing per @jhinkey . Thanks for keeping tabs!

**Pull request closed without merging**
