### PR TITLE
search 7.x | search experiences blueprints phase 1 | LRDOCS-9189

### PR DESCRIPTION
**Pull request by rbohl**
cc @sez11a (I'm following the earlier convention of sending User Docs through JR, but let me know if that's incorrect, and obviously your additional review is welcomed)
cc @lipusz
https://issues.liferay.com/browse/LRDOCS-9362
https://issues.liferay.com/browse/LRDOCS-9363

This is the tip of the iceberg for Blueprints. The first 2 articles are good enough to get people started but there are additional critical docs to be written. I'll begin on those now that these articles are drafted and SME-reviewed.

An important thing to note: Blueprints isn't released, but it's hard to see it being more than 1-2 weeks away in a 7.4 update. I've used some wishy-washy "will become available" type language in the Search Experiences intro, please let me know if there's a better way.

### CODE REVIEW

**Comment by rbohl** [comment]
@jrhoun if possible can I have an estimate on when you might review this PR? I'm adding a new article and commits to my branch locally, since I have the navigation and the existing articles to reference in there. This is convenient but if it will take a bit of time I should perhaps be working in a separate branch.

**Comment by jrhoun** [comment]
I'll review it this morning @rbohl ! Will try and get it merged before my push to prod this afternoon.

**Comment by jrhoun** [comment]
Merged. Made a few minor changes here: 759f35c456baa8eccb54011de7cead50797db731

I think your wording on availability is fine, though I was tempted to tinker with it. I did crop an image to reduce the whitespace on the bottom of it.  I also fixed an image path to a cog icon (https://github.com/jrhoun/liferay-learn/pull/1337/files#diff-5419ceb4168832880fcdac8c3497b39cbd8deb861421cafdd8a005dfb6dea311R188). There was not cog3 image in the repo, so I just set it to the generic one. Maybe you forgot to add it to your initial push? Either way, I thought it would be good enough to push up even if the cog icon is different.

Thanks @rbohl !

**Comment by rbohl** [comment]
Thanks for getting it in, JR! cog3.png is a file I never committed. I'll try to remember to take care of it with the next batch of docs.

**Pull request closed without merging**
