### PR TITLE
LRDOCS-8203 mobile updates & applying see more option to all landing pages

### PR DESCRIPTION
**Pull request by rdai10**
@jrhoun:
Changes in this pr:

- Updated mobile section spacing for homepage:
image
Can you double check the svgs on your build to make sure they don't look gray like the :point_up: screenshot?
- Updated documentations pages layout to look presentable on mobile:
image
image
- Applied changes to all landing pages and templates to allow the user to click on a three dot icon to see more items on a landing page card. 
In terms of changes to the `landingpage.html` pages, whenever there is the `subsections` property, add `showAll: false,` above `subsections`.

Example: 
```
{
	icon: '#test'',
	sectionName: 'Test',
	sectionURL: 'test.html',
	showAll: false,
	subsections: [
		{
			name: '1',
			url: '/1'
		},
		{
			name: '2',
			url: '/2'
		}
	]
}
```

Going to start fine tuning mobile view after this.

### CODE REVIEW

**Comment by rdai10** [comment]
As of now, accessibility score on both desktop and mobile averages to the following:
image
Main thing we could improve on is various color contrast issues (lack thereof).
For examples:
- The language toggle at the base of the left side nav not having enough color contrast.
image
- The highlight color on search pages 
image

**Comment by jrhoun** [comment]
Just started reviewing!

**Comment by jrhoun** [comment]
The product index page view on mobile doesn't look quite as nice as your screenshot did:

image

But the sub-sections (without icons) looked nice: 
image

**Comment by jrhoun** [comment]
Also just finished a build, and yes -- the resources svgs do look grey to me:

image

**Comment by rdai10** [comment]
Tested the same page on firefox and chrome but can't reproduce your screenshots.
image
image
image

Will send the svg fix in the next pr.

**Comment by rdai10** [comment]
@jrhoun I see, my building is missing the `<meta name="viewport" content="width=device-width, initial-scale=1.0">` header attribute. Will fix in subsequent prs.

**Comment by jrhoun** [comment]
Merged. Thanks!

**Comment by rdai10** [comment]
Followed up at https://github.com/jrhoun/liferay-learn/pull/667

**Pull request closed without merging**
