### PR TITLE
LRDOCS-7534 & LRDOCS-7535 port Segmentation and Personalization 7.2 docs

### PR DESCRIPTION
**Pull request by mwilliams2014**
Links for articles not yet ported marked as TODO

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Updating to match proper formatting for filenames and images

**Comment by mwilliams2014** [comment]
Updated

**Comment by mwilliams2014** [comment]
Adding more info to this for the sponsored dev docs. Will comment here when updated.

**Comment by jrhoun** [comment]
Hi @mwilliams2014 can you double check your articles for image alt text in the markdown that is formatted (Italics or bolding) - those things break the build and it seems like there's at least one instance of that in this pull based on the CI Build breaking. Please re-send once its fixed. Thanks!

**Comment by mwilliams2014** [comment]
Oh. I wasn't aware. Yeah. I'll update and resend tomorrow.

**Pull request closed without merging**
